// Generated by CoffeeScript 1.12.4
(function() {
  var Animal, taro;

  Animal = (function() {
    Animal.prototype.atype = "Animal";

    function Animal(name) {
      this.name = name;
    }

    Animal.prototype.print = function() {
      return console.log("name is " + this.name + ", type is " + this.atype);
    };

    return Animal;

  })();

  taro = new Animal("Taro");

  taro.print();

}).call(this);
