// Generated by CoffeeScript 1.12.4
(function() {
  var name;

  name = 'Joseph';

  if (name.length > 1) {
    console.log("Hello, " + name + "!");
  } else {
    console.log("empty name");
  }

}).call(this);
